name: budget_scouter
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  
  pie_chart: ^5.3.2

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  import_path_converter: ^1.0.1
  import_sorter: ^4.6.0

flutter:
  uses-material-design: true

import_path_converter:
  relative: true
