name: budget_scouter
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.9.3
  flutter_riverpod: ^1.0.0
  font_awesome_flutter: ^10.1.0
  freezed: ^2.0.3+1
  freezed_annotation: ^2.0.3
  json_serializable: ^6.2.0
  pie_chart: ^5.3.2

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  import_path_converter: ^1.0.1
  import_sorter: ^4.6.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/icon.png"

import_path_converter:
  relative: true
